### ISSUE TITLE
(un)pair return null

### ISSUE THREAD

**Issue by alanzbl** [obermillerk/win-bt#1]
in bt.js 
result returns a function that with no status property under it. Maybe something going on with async/await? 
https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncoperation_tresult_

I tested older version 0.1.1 where you used deasync for this. 
It actually works with admin privilege.

**Comment by alanzbl** [comment]
I debugged into source code. unpairAsync and pairAsync wouldn't be passed into the local function under _promisify

**Comment by obermillerk** [comment]
Fixed in version 0.2.2
